In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [4]:
y.grad_fn

In [5]:
z = y * y * 3
out = z.mean()
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [6]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [7]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a, a.requires_grad)

tensor([[ 0.6807,  0.9578],
        [-1.0329,  1.0368]]) False


In [8]:
a.requires_grad_(True)
print(a, a.requires_grad)

tensor([[ 0.6807,  0.9578],
        [-1.0329,  1.0368]], requires_grad=True) True


In [9]:
b = (a * a).sum()
print(b)

tensor(3.5226, grad_fn=<SumBackward0>)


## Gradients

In [10]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [11]:
# x = torch.ones(2, 2, requires_grad = True)
# y = x + 2
# z = y * y * 3
# out = z.mean()

In [12]:
out.backward()

In [13]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


### vector - jacobian product

In [17]:
x = torch.randn(3, requires_grad = True)
y = x * 2

In [18]:
y

tensor([-1.0432,  0.7378, -2.7408], grad_fn=<MulBackward0>)

In [19]:
y.data.norm()

tensor(3.0240)

In [20]:
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([ -534.1082,   377.7573, -1403.2872], grad_fn=<MulBackward0>)


In [21]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [22]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [23]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

True
False


In [24]:
x

tensor([-0.5216,  0.3689, -1.3704], requires_grad=True)

In [25]:
y

tensor([-0.5216,  0.3689, -1.3704])

In [26]:
print(x.eq(y))

tensor([True, True, True])


In [27]:
print(x.eq(y).all())

tensor(True)
